/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsNoComplyRouteImport } from './routes/projects.no-comply'
import { Route as ProjectsLuckyDayCoRouteImport } from './routes/projects.lucky-day-co'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNoComplyRoute = ProjectsNoComplyRouteImport.update({
  id: '/projects/no-comply',
  path: '/projects/no-comply',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLuckyDayCoRoute = ProjectsLuckyDayCoRouteImport.update({
  id: '/projects/lucky-day-co',
  path: '/projects/lucky-day-co',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/lucky-day-co': typeof ProjectsLuckyDayCoRoute
  '/projects/no-comply': typeof ProjectsNoComplyRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/lucky-day-co': typeof ProjectsLuckyDayCoRoute
  '/projects/no-comply': typeof ProjectsNoComplyRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/lucky-day-co': typeof ProjectsLuckyDayCoRoute
  '/projects/no-comply': typeof ProjectsNoComplyRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/projects/lucky-day-co'
    | '/projects/no-comply'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/projects/lucky-day-co'
    | '/projects/no-comply'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/projects/lucky-day-co'
    | '/projects/no-comply'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsLuckyDayCoRoute: typeof ProjectsLuckyDayCoRoute
  ProjectsNoComplyRoute: typeof ProjectsNoComplyRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/no-comply': {
      id: '/projects/no-comply'
      path: '/projects/no-comply'
      fullPath: '/projects/no-comply'
      preLoaderRoute: typeof ProjectsNoComplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/lucky-day-co': {
      id: '/projects/lucky-day-co'
      path: '/projects/lucky-day-co'
      fullPath: '/projects/lucky-day-co'
      preLoaderRoute: typeof ProjectsLuckyDayCoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsLuckyDayCoRoute: ProjectsLuckyDayCoRoute,
  ProjectsNoComplyRoute: ProjectsNoComplyRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
