/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsNoComplyRouteImport } from './routes/projects.no-comply'
import { Route as ProjectsLuckyDayCoRouteImport } from './routes/projects.lucky-day-co'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProjectsNoComplyMediaRouteImport } from './routes/projects.no-comply.media'
import { Route as ProjectsNoComplyCaughtOnFilmRouteImport } from './routes/projects.no-comply.caught-on-film'
import { Route as ProjectsNoComplyAboutRouteImport } from './routes/projects.no-comply.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNoComplyRoute = ProjectsNoComplyRouteImport.update({
  id: '/projects/no-comply',
  path: '/projects/no-comply',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLuckyDayCoRoute = ProjectsLuckyDayCoRouteImport.update({
  id: '/projects/lucky-day-co',
  path: '/projects/lucky-day-co',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNoComplyMediaRoute = ProjectsNoComplyMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => ProjectsNoComplyRoute,
} as any)
const ProjectsNoComplyCaughtOnFilmRoute =
  ProjectsNoComplyCaughtOnFilmRouteImport.update({
    id: '/caught-on-film',
    path: '/caught-on-film',
    getParentRoute: () => ProjectsNoComplyRoute,
  } as any)
const ProjectsNoComplyAboutRoute = ProjectsNoComplyAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProjectsNoComplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/lucky-day-co': typeof ProjectsLuckyDayCoRoute
  '/projects/no-comply': typeof ProjectsNoComplyRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/no-comply/about': typeof ProjectsNoComplyAboutRoute
  '/projects/no-comply/caught-on-film': typeof ProjectsNoComplyCaughtOnFilmRoute
  '/projects/no-comply/media': typeof ProjectsNoComplyMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/lucky-day-co': typeof ProjectsLuckyDayCoRoute
  '/projects/no-comply': typeof ProjectsNoComplyRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/no-comply/about': typeof ProjectsNoComplyAboutRoute
  '/projects/no-comply/caught-on-film': typeof ProjectsNoComplyCaughtOnFilmRoute
  '/projects/no-comply/media': typeof ProjectsNoComplyMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/lucky-day-co': typeof ProjectsLuckyDayCoRoute
  '/projects/no-comply': typeof ProjectsNoComplyRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/no-comply/about': typeof ProjectsNoComplyAboutRoute
  '/projects/no-comply/caught-on-film': typeof ProjectsNoComplyCaughtOnFilmRoute
  '/projects/no-comply/media': typeof ProjectsNoComplyMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/products/$slug'
    | '/projects/lucky-day-co'
    | '/projects/no-comply'
    | '/projects/'
    | '/projects/no-comply/about'
    | '/projects/no-comply/caught-on-film'
    | '/projects/no-comply/media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/products/$slug'
    | '/projects/lucky-day-co'
    | '/projects/no-comply'
    | '/projects'
    | '/projects/no-comply/about'
    | '/projects/no-comply/caught-on-film'
    | '/projects/no-comply/media'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/products/$slug'
    | '/projects/lucky-day-co'
    | '/projects/no-comply'
    | '/projects/'
    | '/projects/no-comply/about'
    | '/projects/no-comply/caught-on-film'
    | '/projects/no-comply/media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProjectsLuckyDayCoRoute: typeof ProjectsLuckyDayCoRoute
  ProjectsNoComplyRoute: typeof ProjectsNoComplyRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/no-comply': {
      id: '/projects/no-comply'
      path: '/projects/no-comply'
      fullPath: '/projects/no-comply'
      preLoaderRoute: typeof ProjectsNoComplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/lucky-day-co': {
      id: '/projects/lucky-day-co'
      path: '/projects/lucky-day-co'
      fullPath: '/projects/lucky-day-co'
      preLoaderRoute: typeof ProjectsLuckyDayCoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/no-comply/media': {
      id: '/projects/no-comply/media'
      path: '/media'
      fullPath: '/projects/no-comply/media'
      preLoaderRoute: typeof ProjectsNoComplyMediaRouteImport
      parentRoute: typeof ProjectsNoComplyRoute
    }
    '/projects/no-comply/caught-on-film': {
      id: '/projects/no-comply/caught-on-film'
      path: '/caught-on-film'
      fullPath: '/projects/no-comply/caught-on-film'
      preLoaderRoute: typeof ProjectsNoComplyCaughtOnFilmRouteImport
      parentRoute: typeof ProjectsNoComplyRoute
    }
    '/projects/no-comply/about': {
      id: '/projects/no-comply/about'
      path: '/about'
      fullPath: '/projects/no-comply/about'
      preLoaderRoute: typeof ProjectsNoComplyAboutRouteImport
      parentRoute: typeof ProjectsNoComplyRoute
    }
  }
}

interface ProjectsNoComplyRouteChildren {
  ProjectsNoComplyAboutRoute: typeof ProjectsNoComplyAboutRoute
  ProjectsNoComplyCaughtOnFilmRoute: typeof ProjectsNoComplyCaughtOnFilmRoute
  ProjectsNoComplyMediaRoute: typeof ProjectsNoComplyMediaRoute
}

const ProjectsNoComplyRouteChildren: ProjectsNoComplyRouteChildren = {
  ProjectsNoComplyAboutRoute: ProjectsNoComplyAboutRoute,
  ProjectsNoComplyCaughtOnFilmRoute: ProjectsNoComplyCaughtOnFilmRoute,
  ProjectsNoComplyMediaRoute: ProjectsNoComplyMediaRoute,
}

const ProjectsNoComplyRouteWithChildren =
  ProjectsNoComplyRoute._addFileChildren(ProjectsNoComplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProjectsLuckyDayCoRoute: ProjectsLuckyDayCoRoute,
  ProjectsNoComplyRoute: ProjectsNoComplyRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
